### ISSUE TITLE
ngx-progressbar not compatible with the rxjs (6.1.0)

### ISSUE THREAD

**Issue by yhardi** [MurhafSousli/ngx-progressbar#166] opened 2018-05-14 09:09 UTC
### ngx-progressbar not compatible with the rxjs (6.1.0)
```
In angular 6 (rxjs 6.1.0) the ngx-progressbar does not work and the ng build command shows the following error

ERROR in node_modules/ngx-progressbar/src/services/interceptor.provider.d.ts(2,10): error TS2305: Module '"/home/youness/ctdev/sources/monitor-tools/status-webapp/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/ngx-progressbar/src/services/progress.service.d.ts(1,10): error TS2305: Module '"/home/youness/ctdev/sources/monitor-tools/status-webapp/node_modules/rxjs/Subject"' has no exported member 'Subject'.
node_modules/ngx-progressbar/src/services/progress.service.d.ts(3,10): error TS2305: Module '"/home/youness/ctdev/sources/monitor-tools/status-webapp/node_modules/rxjs/BehaviorSubject"' has no exported member 'BehaviorSubject'.
node_modules/rxjs/BehaviorSubject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/BehaviorSubject'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
node_modules/rxjs/Rx.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat'.
node_modules/rxjs/Subject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Subject'.

```

### Version
2.1.1

### Desired functionality
ngx-progessbar to be compatible with the rxjs 6.1.0

### Details that might be useful
In the new rxjs (6.1.0) :
import { Observable } from 'rxjs/Observable' should be remplaced by import { Observable } from 'rxjs';
....

**Comment by MurhafSousli** [comment] 2018-05-14 09:17
duplicate of #165 #164 #161 #160 #143

**Closed by MurhafSousli** 2018-05-14 09:17 UTC
