### ISSUE TITLE
Error with angular 7

### ISSUE THREAD

**Issue by bogalex93** [MurhafSousli/ngx-progressbar#241] opened 2018-12-31 13:13 UTC
### Bug Report 
Error in the browser console.
TypeError: rxjs_Observable__WEBPACK_IMPORTED_MODULE_3__.Observable.timer is not a function

### OS and Version?
 Windows 10.

**Comment by fchiumeo** [comment] 2018-12-31 16:05
what version of rxjs used?

**Comment by bogalex93** [comment] 2018-12-31 17:08
Hi, thank you for the quick response,
My version is ^6.3.3.

**Comment by MurhafSousli** [comment] 2018-12-31 18:56
The problem is with your project, closing this as does not follow issue template and I don't think anyone can help you with the info you provided

**Closed by MurhafSousli** 2018-12-31 18:56 UTC
