### ISSUE TITLE
error TS2305: Module '"node_modules/rxjs/Observable"' has no exported member 'Observable'.

### ISSUE THREAD

**Issue by krreet** [MurhafSousli/ngx-progressbar#183] opened 2018-05-31 12:45 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### Repro steps

error TS2305: Module '"node_modules/rxjs/Observable"' has no exported member 'Observable'.

**Comment by MurhafSousli** [comment] 2018-05-31 14:02
For Angular 5.x use version 4.3.0

Duplicate of #166 #165 #164 #161 #160 #143

**Closed by MurhafSousli** 2018-05-31 14:02 UTC

**Comment by krreet** [comment] 2018-06-05 05:09
unable to install 4.3.0 pls help
npm install ngx-progressbar@4.3.0 --save
npm ERR! code ETARGET
npm ERR! notarget No matching version found for ngx-progressbar@4.3.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by MurhafSousli** [comment] 2018-06-05 06:18
@krreet `@ngx-progressbar/core` not `ngx-progressbar`!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
