### ISSUE TITLE
NgProgressModule and NgProgressHttpModule not working in ng-package build

### ISSUE THREAD

**Issue by bitbeter** [MurhafSousli/ngx-progressbar#165] opened 2018-05-12 13:28 UTC
I'm working with `Angular 6` and I a used `Angular cli` to generate library with it.
When I import NgProgressModule and NgProgressHttpModule and `Build` this error will be thrown:

```
BUILD ERROR
Error during template compile of 'CommonsModule'
  Function calls are not supported in decorators but 'NgProgressModule' was called.
: Unexpected value 'undefined' imported by the module 'CommonsModule in 
 /projects/commons/src/lib/commons.module.ts'
: Unexpected value 'NgProgressHttpModule in 
node_modules/@ngx-progressbar/http/lib/ng-progress-http.module.d.ts' imported by the module 'CommonsModule in 
/projects/commons/src/lib/commons.module.ts'. Please add a @NgModule annotation.
: Can't export value NgProgressModule in 
/node_modules/@ngx-progressbar/core/lib/ng-progress.module.d.ts from CommonsModule in /projects/commons/src/lib/commons.module.ts as it was neither declared nor imported!
: Can't export value NgProgressHttpModule in 
/node_modules/@ngx-progressbar/http/lib/ng-progress-http.module.d.ts from CommonsModule in /projects/commons/src/lib/commons.module.ts as it was neither declared nor imported!
Error during template compile of 'CommonsModule'
  Function calls are not supported in decorators but 'NgProgressModule' was called.
```

i am using @ngx-progressbar-rc.0

**Comment by MurhafSousli** [comment] 2018-05-14 09:17
duplicate of #165 #164 #161 #160 #143

**Closed by MurhafSousli** 2018-05-14 09:17 UTC
