### ISSUE TITLE
Progressbar is not shown while http requests are pending when using NgProgressHttpModule

### ISSUE THREAD

**Issue by Edminsson** [MurhafSousli/ngx-progressbar#253] opened 2019-03-18 07:12 UTC
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
Windows 7

### Versions
Angular 7.1.3

### Description
I have an issue with NgProgressHttpModule.
I have an router guard that makes a http request that completes before some other requests are made. This first request also completes the progressbar but since the status seems to change asynchronously the other requests are called while the active flag still is true and hence the progressbar is not started again. So what happens is that the progressbar is not shown while calls are pending.
I've made [this example](https://stackblitz.com/edit/angular-aqkxlk) to illustrate the problem. I'm not using NgProgressHttpModule here but I've copied the essential code in order to add some console.log calls to show what happens. I also have an example that uses NgProgressHttpModule and it behaves in the same way.
If I skip the control of the isStarted flag in the interceptor and always make a call to the start method it seems to work like it's supposed to do.

**Comment by MurhafSousli** [comment] 2020-01-11 00:14
The issue isn't unclear! I am sorry but I cannot understand the logs are for. I know it's too late but I am closing for now... if you still have an issue, please reopen and add more details in a readable way

**Comment by MurhafSousli** [comment] 2020-01-11 03:04
Ok, I figured what was causing the issue now. Basically you were starting the next request as soon as the previous one finishes.

In progress bar code when it completes, the state uses a tiny delay to properly animate and hide the progress bar.

```ts
  private onComplete(config: NgProgressConfig): Observable<any> {
    return !this.isStarted ? EMPTY : of({}).pipe(
      // Completes the progress
      tap(() => this.setState({ value: 100 })),

      // Hides the progress bar after a tiny delay
      delay(config.speed * 1.7),
      tap(() => this.setState({ active: false })),

      // Resets the progress state
      delay(config.speed),
      tap(() => this.setState({ value: 0 }))
    );
  }
```

As you can see the active is set to false after (200 * 1.7), but you were starting the next http request before that line gets executed.

**Closed** 2020-01-12 02:15 UTC
Labels: bug
